name: Tests
on: [push]

jobs:
  build-temp-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: build-temp-container
        run: |
          echo ${PASSWORD} | docker login -u $USERNAME --password-stdin
          docker build -t hamelsmu/app-token:temp -f prebuild.Dockerfile .
          docker push hamelsmu/app-token:temp
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  test-container:
    needs: [build-temp-container]
    runs-on: ubuntu-latest
    steps:
  
    - uses: actions/checkout@master
      
    # tested with https://github.com/apps/fastpages-chatops
    - name: test
      id: test
      uses: docker://hamelsmu/app-token:temp
      env:
        INPUT_APP_PEM: ${{ secrets.APP_PEM }}
        INPUT_APP_ID: ${{ secrets.APP_ID }}

    - name: pre-build action image
      run: |
        cd $GITHUB_WORKSPACE
        echo ${PASSWORD} | docker login -u $USERNAME --password-stdin
        docker build -t hamelsmu/app-token -f prebuild.Dockerfile .
        docker push hamelsmu/app-token 
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

       # tested withhttps://github.com/apps/fastpages-chatops
    - name: final-test
      uses: machine-learning-apps/actions-app-token@master
      with:
        APP_PEM: ${{ secrets.APP_PEM }}
        APP_ID: ${{ secrets.APP_ID }}